### ISSUE TITLE
Deploy Front End For Submission

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/my-ai-app#13]
We need to deploy the front end so that we can submit it! We also need to record a video.

**Comment by mdwiltfong** [comment]
We have deployed the front end, we now need to make a video: 
https://my-ai-app-amber.vercel.app/

**Comment by mdwiltfong** [comment]
We will shoot for a 2 min video. Further details later.

**Comment by Jamesllllllllll** [comment]
I needed to create a new repo on my account to do rapid changes, here is the final URL we can submit to the hackathon:

https://doc-inspector-fe.vercel.app/
