### ISSUE TITLE
Enable Users to upload document to app

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/my-ai-app#2]
A user can not start a conversation with an assistant until they load a document. The UI needs to guide the user into doing so. This means that the app has to be able to access the documents api, and accept PDFs or word documents from the user. 

Only after uploading a document will the user be able to begin chatting with the assistant

**Comment by Jamesllllllllll** [comment]
This branch has a working document uploader: https://github.com/mdwiltfong/my-ai-app/tree/enhancement/DocumentUpload

It successfully creates a record in the Gadget back-end **Document** Data Model.

In this branch I also set up a bit more Gadget boilerplate. I created a Provider to wrap the pages rendered within the root layout with the api. The catch was I had to use the 'use client' directive which shouldn't happen in the root layout AFAIK.
